name: Deploy to EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: dev
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION  : ${{ secrets.AWS_REGION }}

  deploy-prod:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION  : ${{ secrets.AWS_REGION }}

  notify:
    needs: [deploy-dev, deploy-prod]
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Success Status Message
        run: echo "Deployment Succeeded!"

